### ISSUE TITLE
Create a Helm repository

### ISSUE THREAD

**Issue by Darkness4** [SquareFactory/ClusterFactory-CE#127]
```yaml
name: Helm CI
on:
  push:
    paths:
      - .github/workflows/helm.yaml
      - helm/**
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_RELEASE_NAME_TEMPLATE: 'chart-{{ .Name }}-{{ .Version }}'

```
