### ISSUE TITLE
Replace all the helm applications and use the subchart pattern

### ISSUE THREAD

**Issue by Darkness4** [SquareFactory/ClusterFactory-CE#55]
Because we are declaring all the values inside the `application.yaml`, this is **not** GitOps friendly. We have to use the **subchart** pattern.

Example:

Create a chart repo with only:

```
app-subchart/
├── Chart.yaml
└── values.yaml
```

**Chart.yaml**

```yaml
apiVersion: v2
name: wordpress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "9.0.3"

dependencies:
  - name: wordpress
    version: 9.0.3
    repository: https://charts.helm.sh/stable
```

Not only it solves every problem with GitOps, but it is the recommended solution: https://github.com/argoproj/argocd-example-apps/blob/master/helm-dependency

Reference: https://www.youtube.com/watch?v=VyuVFtp2-2M

This is a heavy breaking change as it changes all the helm applications.
