### ISSUE TITLE
Enable HTTP3 on Traefik

### ISSUE THREAD

**Issue by Darkness4** [SquareFactory/ClusterFactory-CE#67]
Enabling HTTP3 is easy with Traefik:

```yaml
experimental:
  http3:
    enabled: true

ports:
  websecure:
    port: 443
    http3: true
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
```

Remember to add port UDP redirection on the routers!
